Fix goroutine leak in socket.sender
nanomsg/mangos pull request #245
Opened 2021-12-15 23:38 UTC by davidmirza408

2021-12-15 23:42 UTC, davidmirza408 commented
mistake

2022-01-19 18:10 UTC, davidmirza408 commented
@gdamore can you review my PR?

2022-01-19 23:22 UTC, gdamore requested changes

2022-01-19 23:22 UTC, gdamore commented on protocol/xpush/xpush.go
> +	s.cv.Signal()
This should be s.cv.Broadcast() (because what if multiple threads are waiting to send?)

2022-01-28 21:56 UTC, davidmirza408 commented
@gdamore thanks for the review.  I updated the PR.

2022-03-01 07:04 UTC, gdamore approved these changes

2022-03-01 07:05 UTC, merged